name: Build Java Jar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Download and Install ProtocolLib manually
      run: |
        wget https://github.com/dmulloy2/ProtocolLib/releases/download/5.4.0/ProtocolLib.jar -O ProtocolLib.jar
        mvn install:install-file -Dfile=ProtocolLib.jar -DgroupId=com.comphenix.protocol -DartifactId=ProtocolLib -Dversion=5.4.0 -Dpackaging=jar

    - name: Build with Maven
      run: mvn clean package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LootableCorpses-Jar
        path: target/*.jar